export const SOURCES=Object.freeze(['live','history','replay'])
const SPEEDS=Object.freeze([.1,.25,.5,1,2,4,8,16])
const valid=x=>x&&Number.isSafeInteger(x.sequence)&&Number.isFinite(x.eventTimeMs)&&Number.isFinite(x.value)&&Number.isFinite(x.quality)&&x.quality>=0&&x.quality<=1
const filtered=(xs,f)=>xs.filter(x=>x.quality>=f.minQuality&&(!f.series||x.series===f.series))
const normalized=(items,series='aggregate')=>items.map((x,index)=>({sequence:x.sequence??index+1,eventTimeMs:x.eventTimeMs??x.event_time_ms??x.start_ms,value:x.value??x.mean,quality:x.quality?.score??x.min_quality??1,series:x.series??series}))
const frozen=s=>Object.freeze({...s,samples:Object.freeze(s.samples),range:Object.freeze(s.range),filters:Object.freeze(s.filters),bookmarks:Object.freeze(s.bookmarks)})

export function createTimelineState({capacity=512,source='live',now=()=>Date.now()}={}){
 if(!Number.isSafeInteger(capacity)||capacity<2||capacity>10000||!SOURCES.includes(source))throw new TypeError('invalid timeline bounds')
 let s=frozen({source,connection:'disconnected',samples:[],dropped:0,gap:null,cursorMs:null,range:{startMs:0,endMs:0},filters:{minQuality:0,series:null},speed:1,playing:false,bookmarks:[],updatedAtMs:0});const listeners=new Set();const set=n=>{s=frozen(n);listeners.forEach(f=>f(s));return s}
 return Object.freeze({getState:()=>s,subscribe(f){listeners.add(f);return()=>listeners.delete(f)},setSource(v){if(!SOURCES.includes(v))throw new TypeError('invalid source');return set({...s,source:v,connection:'disconnected',samples:[],gap:null,cursorMs:null,playing:false})},connect(){return set({...s,connection:'connected',updatedAtMs:now()})},disconnect(){return set({...s,connection:'disconnected',playing:false})},stale(){return set({...s,connection:'stale',playing:false})},conflict(){return set({...s,connection:'conflict',playing:false})},ingest(input,{gap=null}={}){if(!Array.isArray(input)||input.some(x=>!valid(x)))throw new TypeError('invalid samples');let conflict=false;const all=[...s.samples];for(const x of input){const old=all.find(y=>y.sequence===x.sequence);if(old&&JSON.stringify(old)!==JSON.stringify(x))conflict=true;else if(!old)all.push(Object.freeze({...x}))}all.sort((a,b)=>a.sequence-b.sequence);const overflow=Math.max(0,all.length-capacity),samples=all.slice(overflow),shown=filtered(samples,s.filters),range=shown.length?{startMs:shown[0].eventTimeMs,endMs:shown.at(-1).eventTimeMs}:s.range;return set({...s,samples,dropped:s.dropped+overflow+(gap?.dropped??0),gap:gap?Object.freeze({...gap}):s.gap,range,cursorMs:s.cursorMs??range.endMs,connection:conflict?'conflict':'connected',playing:conflict?false:s.playing,updatedAtMs:now()})},setRange(startMs,endMs){if(!Number.isFinite(startMs)||!Number.isFinite(endMs)||startMs>=endMs)throw new TypeError('invalid range');return set({...s,range:{startMs,endMs},cursorMs:Math.min(endMs,Math.max(startMs,s.cursorMs??endMs))})},setFilters(f){const n={...s.filters,...f};if(!Number.isFinite(n.minQuality)||n.minQuality<0||n.minQuality>1)throw new TypeError('invalid quality');return set({...s,filters:n})},seek(ms){if(s.source!=='replay'||!Number.isFinite(ms)||ms<s.range.startMs||ms>s.range.endMs)throw new TypeError('invalid seek');return set({...s,cursorMs:ms,playing:false})},step(direction=1){if(s.source!=='replay'||![1,-1].includes(direction))throw new TypeError('invalid step');const times=filtered(s.samples,s.filters).map(x=>x.eventTimeMs),next=direction>0?times.find(x=>x>(s.cursorMs??-Infinity)):[...times].reverse().find(x=>x<(s.cursorMs??Infinity));return next===undefined?s:set({...s,cursorMs:next,playing:false})},play(){if(s.source!=='replay'||s.connection!=='connected')throw new TypeError('replay unavailable');return set({...s,playing:true})},pause(){return set({...s,playing:false})},setSpeed(v){if(!SPEEDS.includes(v))throw new TypeError('invalid speed');return set({...s,speed:v})},bookmark(){if(s.source!=='replay'||s.cursorMs===null)throw new TypeError('bookmark unavailable');return set({...s,bookmarks:[...new Set([...s.bookmarks,s.cursorMs])].sort((a,b)=>a-b)})},visible(){return filtered(s.samples,s.filters).filter(x=>x.eventTimeMs>=s.range.startMs&&x.eventTimeMs<=s.range.endMs)}})
}

export function createTimelineGateway({gateway,timeline}){let stream;return Object.freeze({startLive(path='/api/v1/streams/observations'){timeline.setSource('live');stream=gateway.stream(path,m=>timeline.ingest(normalized(m.samples??[m.payload??m]),{gap:m.gap}),x=>x.state==='unavailable'&&timeline.disconnect());return stream},async history(query,options){timeline.setSource('history');try{const page=await gateway.query(query,options);timeline.ingest(normalized(page.samples??page.buckets??[],query.series),{gap:page.gap});return page}catch(e){e.code==='CURSOR_CONFLICT'?timeline.conflict():timeline.disconnect();throw e}},loadReplay(samples){timeline.setSource('replay');timeline.connect();timeline.ingest(normalized(samples))},close(){stream?.close();timeline.disconnect()}})}
