import {describe,expect,it} from 'vitest'
import {breadcrumbs,destructivePreview,evidenceInspector,exportMetadata,schemaForm,statePanel,tabs} from './interaction.js'

describe('shared ADR-061 interaction contracts',()=>{
  it('renders deep breadcrumbs and accessible tabs',()=>{expect(breadcrumbs({id:'radio',label:'Radio',detail:['capture-12']})).toContain('aria-current="page"');expect(tabs({id:'radio',active:'live',items:[{id:'live',label:'Live',href:'#/radio?tab=live'}]})).toContain('aria-selected="true"')})
  it('supports every typed state and rejects invented states',()=>{for(const state of ['loading','empty','disconnected','stale','unauthorized','out-of-scope','experimental','blocked','conflict','partial','fault'])expect(statePanel(state)).toContain(`data-state="${state}"`);expect(()=>statePanel('fine')).toThrow()})
  it('renders labelled drawers and escapes hostile provenance',()=>{const html=evidenceInspector({digest:'<script>',scope:'participant/a',lineage:['<img>']});expect(html).toContain('role="complementary"');expect(html).not.toContain('<script>');expect(html).not.toContain('<img>')})
  it('requires a server challenge before destructive submission',()=>{const preview=destructivePreview({action:'Delete',scope:'participant/a',consequences:['Key erasure'],version:7});expect(preview).toContain('data-server-authority="required"');expect(preview).toContain('value="confirm" disabled');const challenged=destructivePreview({action:'Delete',scope:'participant/a',consequences:[],version:7,challenge:{nonce:'n-1'}});expect(challenged).toContain('data-challenge="n-1"');expect(challenged).not.toContain('value="confirm" disabled')})
  it('preserves export and form contract metadata',()=>{expect(exportMetadata({title:'Replay',scope:'site/a',units:'normalized',timeBasis:'event time',source:'observation',quality:'qualified',freshness:'historical',digest:'sha256:a'})).toContain('data-print-preserve="true"');const form=schemaForm({id:'consent',title:'Consent',version:9,fields:[{name:'purpose',label:'Purpose',required:true}],errors:{purpose:'Required'}});expect(form).toContain('data-schema-version="9"');expect(form).toContain('aria-invalid="true"');expect(form).toContain('name="expectedVersion"')})
})
