import { escapeHtml } from './primitives.js'

export const VIEW_STATES=Object.freeze(['loading','empty','disconnected','stale','unauthorized','out-of-scope','experimental','blocked','conflict','partial','fault'])

export function breadcrumbs(route) { const parts=[{label:route.label,href:`#/${route.id}`}].concat((route.detail??[]).map((part,index)=>({label:part.replaceAll('-',' '),href:`#/${route.id}/${route.detail.slice(0,index+1).join('/')}`})))
  return `<nav class="breadcrumbs" aria-label="Breadcrumb">${parts.map((part,index)=>index===parts.length-1?`<span aria-current="page">${escapeHtml(part.label)}</span>`:`<a href="${escapeHtml(part.href)}">${escapeHtml(part.label)}</a><i aria-hidden="true">/</i>`).join('')}</nav>` }

export function tabs({id,items,active}) { return `<div class="workbench-tabs" role="tablist" aria-label="${escapeHtml(id)} views">${items.map(item=>`<a role="tab" aria-selected="${item.id===active}" href="${escapeHtml(item.href)}">${escapeHtml(item.label)}</a>`).join('')}</div>` }

export function statePanel(state,{title='Workspace unavailable',detail='',retry=false}={}) { if(!VIEW_STATES.includes(state))throw new TypeError('unsupported view state')
  return `<section class="view-state state-${state}" role="${state==='fault'||state==='conflict'?'alert':'status'}" data-state="${state}"><strong>${escapeHtml(title)}</strong>${detail?`<p>${escapeHtml(detail)}</p>`:''}${retry?'<button data-view-action="retry">Retry</button>':''}</section>` }

export function drawer({id,title,body,open=true}) { return `<aside id="${escapeHtml(id)}" class="detail-drawer" role="complementary" aria-labelledby="${escapeHtml(id)}-title" ${open?'':'hidden'}><header><h2 id="${escapeHtml(id)}-title">${escapeHtml(title)}</h2><button type="button" aria-label="Close details" data-drawer-close="${escapeHtml(id)}">×</button></header>${body}</aside>` }

export function evidenceInspector({digest,version,clock,scope,lineage=[]}) { return drawer({id:'evidence-inspector',title:'Evidence and provenance',body:`<dl>${[['Digest',digest],['Version',version],['Clock',clock],['Scope',scope]].map(([key,value])=>`<div><dt>${key}</dt><dd>${escapeHtml(value??'Unavailable')}</dd></div>`).join('')}</dl><ol aria-label="Evidence lineage">${lineage.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ol>`}) }

export function destructivePreview({action,scope,consequences,challenge=null,version}) { return `<dialog class="command-dialog" aria-labelledby="destructive-title" data-server-authority="required"><form method="dialog"><h2 id="destructive-title">${escapeHtml(action)}</h2><p>This preview is not authorization. The Rust workflow reauthorizes every step.</p><dl><div><dt>Exact scope</dt><dd>${escapeHtml(scope)}</dd></div><div><dt>Workflow version</dt><dd>${escapeHtml(version)}</dd></div></dl><h3>Consequences</h3><ul>${consequences.map(item=>`<li>${escapeHtml(item)}</li>`).join('')}</ul>${challenge?`<label>Server challenge: type exact scope<input name="typedScope" autocomplete="off" data-challenge="${escapeHtml(challenge.nonce)}"></label>`:'<p class="warning">Request a fresh server confirmation challenge to continue.</p>'}<footer><button value="cancel">Cancel</button><button value="confirm" ${challenge?'':'disabled'}>Submit to authoritative workflow</button></footer></form></dialog>` }

export function exportMetadata({title,scope,units,timeBasis,source,quality,freshness,status='authorized export',digest}) { return `<header class="export-metadata" data-print-preserve="true"><h1>${escapeHtml(title)}</h1><dl>${[['Scope',scope],['Units',units],['Time basis',timeBasis],['Source',source],['Quality',quality],['Freshness',freshness],['Status',status],['Evidence digest',digest]].map(([key,value])=>`<div><dt>${key}</dt><dd>${escapeHtml(value??'Not supplied')}</dd></div>`).join('')}</dl></header>` }

export function schemaForm({id,title,version,fields,errors={}}) { return `<form id="${escapeHtml(id)}" data-schema-version="${escapeHtml(version)}" novalidate><h2>${escapeHtml(title)}</h2>${fields.map(field=>`<label>${escapeHtml(field.label)}<input name="${escapeHtml(field.name)}" type="${escapeHtml(field.type??'text')}" ${field.required?'required':''} aria-invalid="${Boolean(errors[field.name])}" ${errors[field.name]?`aria-describedby="${escapeHtml(field.name)}-error"`:''}></label>${errors[field.name]?`<p id="${escapeHtml(field.name)}-error" class="field-error">${escapeHtml(errors[field.name])}</p>`:''}`).join('')}<input type="hidden" name="expectedVersion" value="${escapeHtml(version)}"><button type="submit">Validate with server</button></form>` }
