import { fixtureEnvelope as e, fixtureMetrics as m } from '../fixtures/read-models.js'
import { badge, metric, panel } from './primitives.js'
import { dataTable, inspector, liveChart, timeline, wizard, workflowCard } from './workbench.js'
import { timelineWorkbench } from './timeline-workbench.js'
import { createTimelineState } from '../state/timeline.js'
import { destructivePreview, exportMetadata, tabs } from './interaction.js'

const rows = (items) => `<dl class="data-list">${items.map(([a,b]) => `<div><dt>${a}</dt><dd>${b}</dd></div>`).join('')}</dl>`
const provenance = () => `<footer class="provenance">Sequence ${e.sequence} · ${e.emittedAt} · ${e.provenance}</footer>`
const line = () => `<div class="signal-ribbon" role="img" aria-label="Illustrative bounded signal history"><i></i><i></i><i></i><i></i><i></i></div>`
const scene = (kind, label) => `<div class="scene-slot" data-scene="${kind}"><p>Loading optional ${label}…</p></div>`

const content = {
 overview: () => `${panel('System pulse', `<div class="metrics">${metric('Capture',m.capture)}${metric('Signal quality',`${m.signalQuality*100}%`)}${metric('Latency',`${m.latencyMs} ms`)}${metric('Queue',`${m.queue*100}%`)}</div>${line()}`, 'Authorized read model')}${panel('Projection boundary', rows([['Approved projection','Baseline / no claim'],['Respiration','Abstained'],['Reason',m.respirationReason],['Operating envelope',m.operatingEnvelope]]))}`,
 topology: () => `${panel('Bounded RF room topology', '<div id="topology-scene" class="scene-slot" data-scene="topology"><p>Loading optional spatial view…</p></div>', 'Illustrative · not a localization claim')}${panel('Geometry evidence', rows([['Device profile','CrowPi qualified fixture'],['Scale','Illustrative'],['Continuity','98.2%'],['Calibration','Bound to fixture digest']]))}`,
 radio: () => `${panel('Acquisition stream', `<div class="metrics">${metric('Packets / sec',m.packetRate)}${metric('Sequence gaps','1.8%')}${metric('Backpressure','Nominal')}${metric('AP link','Healthy')}</div>${line()}`, 'Diagnostic role · redacted')}${panel('Compatibility', rows([['Adapter','Fixture CSI adapter'],['Firmware','Verified manifest'],['Replay','Deterministic / isolated'],['Raw CSI','Restricted']]))}`,
 signals: () => `${panel('Observation window', `${line()}${rows([['Window','20.0 seconds'],['Missingness','0.6%'],['Contamination','Below threshold'],['Artifact digest','sha256:…57c9']])}`, 'Observations only · no cognitive interpretation')}${panel('Window lineage',scene('provenance','evidence provenance'),'Bounded event-time flow')}`,
 physiology: () => `${panel('Respiration estimator', `<div class="hero-state">${badge('ABSTAINED','blocked')}<strong>No rate displayed</strong><p>${m.respirationReason}. Non-medical research capability.</p></div>`, 'Capability fail-closed')}${panel('Evidence lineage', rows([['Promotion','Not promoted'],['Calibration','Fixture only'],['Coverage','Outside production evidence'],['Reference','Respiratory belt absent']]))}`,
 inference: () => `${panel('State projection', `<div class="hero-state">${badge('NO CLAIM','neutral')}<strong>Baseline observation</strong><p>Out-of-distribution and scope gates remain authoritative in Rust.</p></div>`, 'Policy-approved copy')}${panel('Claim boundary', rows([['Task workload','Experimental / isolated'],['Temporal debounce','Applied'],['Valence','Not implemented'],['Decision phase','Not implemented']]))}`,
 memory: () => `${panel('Participant memory', rows([['Scope','Current participant only'],['Anchors','12 consent-bound'],['Candidate adaptations','2 quarantined'],['Cross-participant queries','Prohibited']]), 'Cryptographically scoped')}${panel('Scoped retrieval neighborhood',scene('neighborhood','participant neighborhood'),'Current participant only')}${panel('Data rights', '<div class="action-grid"><button>View manifest</button><button>Prepare export</button><button class="danger">Dry-run deletion</button></div>')}`,
 device: () => `${panel('Physical projection parity', '<div class="device-preview"><div class="oled">SENSING<br>NO CLAIM</div><div class="rgb" aria-label="Blue RGB status: sensing active"></div></div>', 'OLED + text-plus-color')}${panel('Peripheral state', rows([['Touch','Debounced / confirmation required'],['DHT','Covariate healthy'],['Brightness','68%'],['Physical off','Available']]))}`,
 consent: () => `${panel('Active authorization', rows([['Participant','Pseudonymous session'],['Space','Qualified room A'],['Purpose','Research observation'],['Expires','54 minutes'],['Retention','7 days']]), 'Purpose-bound')}${panel('Governed actions', '<div class="action-grid"><button>Review policy</button><button>Renew authorization</button><button class="danger">Revoke & stop capture</button></div>')}`,
 validation: () => `${panel('Frozen experiment', rows([['Protocol','RESP-VAL-003 (frozen)'],['Dataset card','Complete'],['Leakage checks','Pass'],['Reference sync','Pending real belt'],['Promotion decision','Blocked']]), 'Negative results retained')}${panel('Evidence provenance',scene('provenance','validation provenance'),'Immutable dependencies')}${panel('Reproducibility', '<button>Export signed validation report</button>')}`,
 models: () => `${panel('Capability registry', rows([['Respiration baseline','Quarantined'],['Task workload','Experimental'],['Known-answer health','Pass (fixture)'],['Signed capability policy','Missing production evidence']]), 'Packages signed · activation atomic')}${panel('Capability constellation',scene('constellation','model dependency view'),'Experimental watermark')}${panel('Model safeguards', rows([['Calibration','Fixture only'],['OOD','Fail closed'],['Selective risk','Enforced'],['Rollback','Prior package retained']]))}`,
 reliability: () => `${panel('Pipeline health', '<div id="pipeline-scene" class="scene-slot" data-scene="pipeline"><p>Loading optional dependency view…</p></div>', 'Payload-free topology')}${panel('Resource envelope', `<div class="metrics">${metric('Thermal',`${m.thermalC} °C`)}${metric('Power',`${m.powerW} W`)}${metric('Watchdogs','Healthy')}${metric('Freshness','Current')}</div>`)}`,
 commissioning: () => `${panel('Site qualification', '<div class="checklist"><p>✓ Hardware & firmware</p><p>✓ Link and packet continuity</p><p>✓ Consent and storage</p><p>◌ Thermal soak — evidence pending</p><p>◌ Exact Pi HIL — evidence pending</p></div>', 'Coverage 11 / 13')}${panel('Qualification coverage',scene('coverage','commissioning coverage'),'Incomplete evidence visible')}${panel('Acceptance', rows([['Signed acceptance','Not issued'],['Recovery mode','Ready'],['Blocked capabilities','2'],['Requalification','Required after hardware change']]))}`,
 operations: () => `${panel('Local operations', '<div class="action-grid"><button>Run doctor</button><button>Capture test</button><button>Hardware probe</button><button>Replay fixture</button><button>Backup check</button><button>Support bundle preview</button></div>', 'Commands reauthorized in Rust')}${panel('Destructive workflows', '<p class="warning">Reset and decommission require dry-run, typed confirmation, and a fresh role-bound session.</p><button class="danger">Open guarded workflows</button>')}`,
 security: () => `${panel('Security posture', rows([['Credential state','Healthy / redacted'],['Update signature','Verified'],['Vulnerabilities','No known release blocker'],['Active incidents','0'],['Capability suspension','Available']]), 'Exploit details withheld')}${panel('Fault containment',scene('containment','containment map'),'Sensitive payloads omitted')}${panel('Incident response', '<div class="action-grid"><button>Verify evidence</button><button>Open response runbook</button><button class="danger">Suspend capability</button></div>')}`,
 readiness: () => `${panel('Production decision', '<div class="readiness-block"><span>NOT_APPROVED</span><p>Software controls cannot replace HIL, human validation, legal approval, pilot, penetration, accessibility, and support evidence.</p></div>', 'Signed decision is authoritative')}${panel('Acceptance dependencies', '<div id="readiness-scene" class="scene-slot" data-scene="readiness"><p>Loading optional dependency map…</p></div>')}${panel('Release evidence', rows([['SBOM & manifest','Complete'],['Pi HIL & soak','Pending'],['Human validation','Pending'],['Legal & jurisdiction','Pending'],['Commercial pilot','Pending'],['Accessibility review','Pending']]))}`,
}

const wave=(base,amplitude,count=48)=>Array.from({length:count},(_,i)=>base+Math.sin(i*.43)*amplitude+Math.cos(i*.17)*amplitude*.35)
const synchronizedTimeline=()=>{const state=createTimelineState({source:'replay'});state.connect();state.ingest(wave(.62,.18).map((value,index)=>({sequence:index+1,eventTimeMs:index*250,value,quality:index%13===0?.72:.96,series:'observation'})));state.setRange(0,11750);return timelineWorkbench(state.getState(),state.visible())}
const steps=(labels,current=1)=>labels.map((label,index)=>({label,state:index<current?'done':index===current?'active':'pending',detail:index<current?'Evidence verified':index===current?'Awaiting operator':'Not started'}))
const detail={
 overview:()=>`${liveChart({label:'Signal integrity',values:wave(91,5),unit:'%',quality:'qualified'})}${timeline()}${dataTable('Active evidence',['Stream','Sequence','Freshness','State'],[['Capture','4,207','34 ms','healthy'],['Observation','1,882','82 ms','qualified'],['Projection','961','114 ms','no claim']])}`,
 topology:()=>`${inspector('Qualified room geometry',[['Profile','room-a/v3'],['AP distance','2.4 m'],['Calibration','sha256:57c9…'],['Scope','single participant']])}${timeline({range:'10 min'})}`,
 radio:()=>`${liveChart({label:'CSI packet continuity',values:wave(187,16),unit:'pkt/s',quality:'1.8% gaps',color:'cyan'})}${dataTable('Capture events',['Event time','Channel','Packets','Quality'],[['18:42:01','36 / 80 MHz','188','good'],['18:42:00','36 / 80 MHz','184','good'],['18:41:59','36 / 80 MHz','151','gap']])}${timeline({range:'5 min'})}`,
 signals:()=>`${synchronizedTimeline()}${dataTable('Evidence windows',['Window','Bounds','Missing','Artifact'],[['obs-881','20.0 s','0.6%','57c9…'],['obs-880','20.0 s','0.4%','a18e…']])}`,
 physiology:()=>`${liveChart({label:'Respiration evidence quality',values:wave(42,9),unit:'%',quality:'abstained',color:'amber'})}${inspector('Why no rate is shown',[['Promotion','not promoted'],['Reference','real belt absent'],['Claim','non-medical'],['Recovery','collect authorized reference']])}`,
 inference:()=>`${timeline({mode:'NO CLAIM',cursor:'18:42:16',range:'2 min'})}${dataTable('Temporal decisions',['Time','Construct','Gate','Projection'],[['18:42:16','baseline','pass','no claim'],['18:42:14','task workload','OOD','abstained'],['18:42:12','baseline','pass','no claim']])}`,
 memory:()=>`${dataTable('Participant anchors',['Anchor','Created','Source','Status'],[['anchor-12','today 18:31','touch','active'],['anchor-11','today 17:14','correction','superseded'],['anchor-10','yesterday','touch','active']])}${workflowCard({title:'Cryptographic deletion',state:'dry-run',progress:25,steps:steps(['Resolve participant scope','Preview affected records','Destroy key material','Rebuild index'],1)})}`,
 device:()=>`${liveChart({label:'Touch debounce signal',values:wave(50,42),unit:'level',quality:'simulator',color:'violet'})}${wizard('Peripheral simulator',['Select signed profile','Exercise OLED / RGB','Test touch debounce','Inject isolated fault'],1)}`,
 consent:()=>`${wizard('Authorization and consent',['Review intended purpose','Confirm participant and space','Choose retention','Sign authorization'],1)}${workflowCard({title:'Immediate revocation',state:'ready',progress:0,steps:steps(['Reauthorize participant','Stop capture','Propagate deletion policy','Issue receipt'],0)})}`,
 validation:()=>`${dataTable('Dataset partitions',['Partition','Participants','Sessions','Leakage'],[['training','18','72','pass'],['calibration','6','24','pass'],['validation','6','24','pass'],['test','6','24','sealed']])}${workflowCard({title:'Capability promotion review',state:'blocked',progress:63,steps:steps(['Freeze protocol','Verify reference synchronization','Evaluate held-out evidence','Named decision'],2)})}`,
 models:()=>`${dataTable('Model registry',['Package','State','KAT','Scope'],[['resp-baseline-v1','quarantined','pass','fixture'],['workload-v0','experimental','pass','isolated'],['previous-safe','retired','pass','rollback']])}${workflowCard({title:'Atomic model activation',state:'awaiting-human',progress:58,steps:steps(['Verify signature','Check compatibility','Run known-answer test','Authorize activation','Post-activation health'],2)})}`,
 reliability:()=>`${liveChart({label:'End-to-end latency',values:wave(34,7),unit:'ms',quality:'within host SLO',color:'cyan'})}${dataTable('Active SLOs',['SLO','Current','Budget','State'],[['Freshness','114 ms','500 ms','pass'],['Queue','12%','70%','pass'],['Thermal','51.2 °C','75 °C','pass'],['Pi soak','—','72 h','pending']])}`,
 commissioning:()=>`${wizard('Site qualification',['Hardware & firmware','Peripheral probe','Power & thermal','AP and packet continuity','Geometry','Consent and storage','Calibration','Capability coverage'],3)}${workflowCard({title:'Signed site acceptance',state:'awaiting-device',progress:46,steps:steps(['Probe','Collect empty-room baseline','Collect participant evidence','Sign exact capability set'],1)})}`,
 operations:()=>`${workflowCard({title:'Signed update activation',state:'ready',progress:34,steps:steps(['Verify bundle','Stage inactive slot','Activate and health-check','Commit or rollback'],1)})}${dataTable('Command receipts',['Receipt','Command','Outcome','Evidence'],[['rcpt-904','doctor','succeeded','9a02…'],['rcpt-903','backup.verify','succeeded','2c10…'],['rcpt-902','update.stage','awaiting-human','78dd…']])}`,
 security:()=>`${dataTable('Security event timeline',['Time','Class','Control','Status'],[['18:39','credential','rate limit','contained'],['17:22','update','signature verify','pass'],['16:04','watchdog','restart budget','recovered']])}${workflowCard({title:'Capability suspension',state:'ready',progress:0,steps:steps(['Declare incident','Preserve evidence','Suspend exact capability','Notify and review'],0)})}`,
 readiness:()=>`${dataTable('Corrective actions',['Criterion','Owner','Due','State'],[['Pi HIL / soak','hardware','unassigned','blocked'],['Human validation','science','unassigned','blocked'],['Legal approval','product','unassigned','blocked']])}`,
}

const destructive={
  consent:{action:'Revoke consent and stop capture',scope:'current participant and qualified space',consequences:['Stop authorized sensing immediately','Apply the governed retention/deletion policy']},
  memory:{action:'Erase participant personalization',scope:'current participant only',consequences:['Destroy participant key material','Rebuild the scoped retrieval index']},
  models:{action:'Revoke model capability',scope:'selected signed model package',consequences:['Prevent new inference service','Retain the immutable audit decision']},
  operations:{action:'Factory reset or decommission',scope:'selected local edge node',consequences:['Stop capture and capabilities','Erase governed local data','Require commissioning before reuse']},
}
export function renderWorkspace(route) { const active=route.tab??'overview';const navigation=tabs({id:route.id,active,items:[['overview','Overview'],['workbench','Workbench'],['evidence','Evidence']].map(([id,label])=>({id,label,href:`#/${route.id}?tab=${id}`}))});const preview=destructive[route.id]?destructivePreview({...destructive[route.id],version:e.sequence}):'';const print=exportMetadata({title:route.label,scope:'role-authorized local projection',units:'as displayed',timeBasis:'event and projection time',source:e.provenance,quality:'policy filtered',freshness:e.emittedAt,status:'fixture / experimental where marked',digest:'sha256:fixture-read-model'});const panels={overview:content[route.id](),workbench:`<section class="workbench-detail">${detail[route.id]?.()??''}</section>`,evidence:`<section class="workbench-detail">${panel('Evidence export',print)}</section>`};return `${navigation}${panels[active]??panels.overview}${preview}<div class="print-only">${print}</div>${provenance()}` }
