import { escapeHtml } from './primitives.js'

const seriesPath=(values,width=640,height=150)=>{const min=Math.min(...values),max=Math.max(...values),span=max-min||1;return values.map((value,index)=>`${index?'L':'M'} ${(index/(values.length-1))*width} ${height-((value-min)/span)*height}`).join(' ')}

export function liveChart({label,values,unit='%',quality='qualified',color='mint'}={}){
  const safe=(values??[]).filter(Number.isFinite).slice(-120)
  if(safe.length<2)return `<section class="chart-shell"><p>Insufficient chart evidence</p></section>`
  return `<section class="chart-shell" aria-label="${escapeHtml(label)} chart"><header><div><span class="chart-live"><i></i>LIVE</span><h3>${escapeHtml(label)}</h3></div><strong>${safe.at(-1).toFixed(1)} <small>${escapeHtml(unit)}</small></strong></header><svg viewBox="0 0 640 150" role="img" aria-label="${escapeHtml(label)} recent values"><defs><linearGradient id="fill-${color}" x1="0" y1="0" x2="0" y2="1"><stop stop-color="var(--${color})" stop-opacity=".35"/><stop offset="1" stop-color="var(--${color})" stop-opacity="0"/></linearGradient></defs><path class="chart-grid" d="M0 30H640M0 75H640M0 120H640"/><path class="chart-fill" fill="url(#fill-${color})" d="${seriesPath(safe)} L640 150 L0 150Z"/><path class="chart-line chart-${color}" d="${seriesPath(safe)}"/><circle cx="640" cy="${150-((safe.at(-1)-Math.min(...safe))/((Math.max(...safe)-Math.min(...safe))||1))*150}" r="4"/></svg><footer><span>−120s</span><span>Quality: ${escapeHtml(quality)}</span><span>Now</span></footer></section>`
}

export function timeline({mode='LIVE',cursor='00:18:42',range='20 min'}={}){return `<section class="timeline" aria-label="Timeline and replay controls"><div class="transport"><button aria-label="Previous frame">‹</button><button aria-label="Play or pause">Ⅱ</button><button aria-label="Next frame">›</button><span>${escapeHtml(mode)}</span></div><div class="scrubber"><i style="left:64%"></i><input type="range" min="0" max="100" value="64" aria-label="Timeline position"><div><span>−${escapeHtml(range)}</span><strong>${escapeHtml(cursor)}</strong><span>now</span></div></div><label>Speed<select><option>1×</option><option>2×</option><option>4×</option><option>0.5×</option></select></label></section>`}

export function dataTable(title,columns,rows){return `<section class="table-shell"><header><div><p class="kicker">Bounded result set</p><h3>${escapeHtml(title)}</h3></div><button>Filter +</button></header><div class="table-scroll"><table><thead><tr>${columns.map(c=>`<th>${escapeHtml(c)}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(row=>`<tr>${row.map(cell=>`<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')}</tbody></table></div><footer><span>${rows.length} records</span><span>Cursor page 1</span><button>Next →</button></footer></section>`}

export function workflowCard({id='',title,state='awaiting-human',progress=null,steps=[],actions=['resume','cancel'],receipt=null,error=null}={}){const determinate=Number.isFinite(progress);return `<section class="workflow-card" ${id?`data-workflow-id="${escapeHtml(id)}"`:''}><header><div><p class="kicker">Durable Rust workflow</p><h3>${escapeHtml(title)}</h3></div><span class="workflow-state">${escapeHtml(state)}</span></header><div class="progress ${determinate?'':'indeterminate'}" role="progressbar" ${determinate?`aria-valuenow="${Math.max(0,Math.min(100,progress))}"`:''} aria-label="Workflow progress"><i style="${determinate?`width:${Math.max(0,Math.min(100,progress))}%`:''}"></i></div>${error?`<p class="workflow-error" role="alert">${escapeHtml(error)}</p>`:''}<ol>${steps.map((step,index)=>`<li class="${step.state}"><span>${index+1}</span><div><strong>${escapeHtml(step.label)}</strong><small>${escapeHtml(step.detail??step.state)}</small></div></li>`).join('')}</ol>${receipt?`<aside class="workflow-receipt"><strong>Authoritative receipt · ${escapeHtml(receipt.outcome)}</strong><small>Audit ${escapeHtml(receipt.auditDigest)}</small></aside>`:''}<footer><button data-workflow-action="evidence">View evidence</button>${actions.includes('confirm')?'<button data-workflow-action="confirm">Confirm exact scope</button>':''}${actions.includes('resume')?'<button data-workflow-action="resume">Resume workflow</button>':''}${actions.includes('cancel')?'<button data-workflow-action="cancel">Cancel safely</button>':''}</footer></section>`}

export function inspector(title,items){return `<aside class="inspector"><header><p class="kicker">Evidence inspector</p><h3>${escapeHtml(title)}</h3><button aria-label="Close inspector">×</button></header><dl>${items.map(([key,value])=>`<div><dt>${escapeHtml(key)}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl><footer>Policy-filtered · Read only</footer></aside>`}

export function wizard(title,steps,current=0){return `<section class="wizard"><header><p class="kicker">Guided workflow</p><h3>${escapeHtml(title)}</h3><span>Step ${current+1} / ${steps.length}</span></header><nav aria-label="Workflow steps">${steps.map((step,index)=>`<span class="${index<current?'done':index===current?'active':''}"><i>${index<current?'✓':index+1}</i>${escapeHtml(step)}</span>`).join('')}</nav><form><label>Evidence reference<input value="fixture:evidence:${current+1}" readonly></label><label>Operator note<textarea placeholder="Add a payload-minimized note"></textarea></label><div><button type="button">Save draft</button><button type="button">Validate & continue →</button></div></form></section>`}
